require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PathsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Path. As you add validations to Path, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PathsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all paths as @paths" do
      path = Path.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:paths)).to eq([path])
    end
  end

  describe "GET #show" do
    it "assigns the requested path as @path" do
      path = Path.create! valid_attributes
      get :show, {:id => path.to_param}, valid_session
      expect(assigns(:path)).to eq(path)
    end
  end

  describe "GET #new" do
    it "assigns a new path as @path" do
      get :new, {}, valid_session
      expect(assigns(:path)).to be_a_new(Path)
    end
  end

  describe "GET #edit" do
    it "assigns the requested path as @path" do
      path = Path.create! valid_attributes
      get :edit, {:id => path.to_param}, valid_session
      expect(assigns(:path)).to eq(path)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Path" do
        expect {
          post :create, {:path => valid_attributes}, valid_session
        }.to change(Path, :count).by(1)
      end

      it "assigns a newly created path as @path" do
        post :create, {:path => valid_attributes}, valid_session
        expect(assigns(:path)).to be_a(Path)
        expect(assigns(:path)).to be_persisted
      end

      it "redirects to the created path" do
        post :create, {:path => valid_attributes}, valid_session
        expect(response).to redirect_to(Path.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved path as @path" do
        post :create, {:path => invalid_attributes}, valid_session
        expect(assigns(:path)).to be_a_new(Path)
      end

      it "re-renders the 'new' template" do
        post :create, {:path => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested path" do
        path = Path.create! valid_attributes
        put :update, {:id => path.to_param, :path => new_attributes}, valid_session
        path.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested path as @path" do
        path = Path.create! valid_attributes
        put :update, {:id => path.to_param, :path => valid_attributes}, valid_session
        expect(assigns(:path)).to eq(path)
      end

      it "redirects to the path" do
        path = Path.create! valid_attributes
        put :update, {:id => path.to_param, :path => valid_attributes}, valid_session
        expect(response).to redirect_to(path)
      end
    end

    context "with invalid params" do
      it "assigns the path as @path" do
        path = Path.create! valid_attributes
        put :update, {:id => path.to_param, :path => invalid_attributes}, valid_session
        expect(assigns(:path)).to eq(path)
      end

      it "re-renders the 'edit' template" do
        path = Path.create! valid_attributes
        put :update, {:id => path.to_param, :path => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested path" do
      path = Path.create! valid_attributes
      expect {
        delete :destroy, {:id => path.to_param}, valid_session
      }.to change(Path, :count).by(-1)
    end

    it "redirects to the paths list" do
      path = Path.create! valid_attributes
      delete :destroy, {:id => path.to_param}, valid_session
      expect(response).to redirect_to(paths_url)
    end
  end

end
